services:
  gogrepo:
    build: .
    container_name: gogrepo
    working_dir: /downloads
    volumes:
      - /data/apps/gog-archive:/downloads  # Where your games will be saved
      - ~/.config/lgogdownloader:/home/goguser/.config/lgogdownloader  # Persist your lgogdownloader config